# Generated by Django 4.0.5 on 2022-11-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.CharField(max_length=250, null=True)),
                ('op2', models.CharField(max_length=250, null=True)),
                ('op3', models.CharField(max_length=250, null=True)),
                ('op4', models.CharField(max_length=250, null=True)),
                ('ans', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
