# Generated by Django 4.0.5 on 2022-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
